version: "3"
services:
  discovery.rtrdc.net:
    image: discovery
    hostname: discovery.rtrdc.net
    ports: 
      - "8080:8080"
  
  foo01.rtrdc.net:
    image: foo
    hostname: foo01.rtrdc.net
    depends_on:
      - "discovery.rtrdc.net"
    ports: 
      - "7080:8080"
      - "9001:9001"

  foo02.rtrdc.net:
    image: foo
    hostname: foo02.rtrdc.net
    depends_on:
      - "discovery.rtrdc.net"
    ports: 
      - "7081:8080"
      - "9002:9001"

  bar01.rtrdc.net:
    image: bar
    hostname: bar01.rtrdc.net
    depends_on:
      - "discovery.rtrdc.net"
    ports: 
      - "6080:8080"
      - "9003:9001"

  bar02.rtrdc.net:
    image: bar
    hostname: bar02.rtrdc.net
    depends_on:
      - "discovery.rtrdc.net"
    ports: 
      - "6081:8080"
      - "9004:9001"
  
  bastion.rtrdc.net:
    image: bastion
    hostname: bastion.rtrdc.net
    depends_on:
      - "discovery.rtrdc.net"